(ns aoc2024.day08-test
  (:require [clojure.test :refer [deftest is testing]]
            [aoc2024.day08 :refer [parse-input solve-part1 solve-part2]]
            [clojure.java.io :as io]))

(def example-input "............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............")

(deftest works
  (testing "with example input"
    (is (= 14 (solve-part1 (parse-input example-input))))
    (is (= 34 (solve-part2 (parse-input example-input)))))

  (testing "with real input"
    (let [input (parse-input (slurp (io/resource "day08.txt")))]
      (is (= 299 (solve-part1 input)))
      (is (= 1032 (solve-part2 input))))))
