(ns aoc2025.day07-test
  (:require [clojure.test :refer [deftest is testing]]
            [aoc2025.day07 :refer [parse-input solve-part1 solve-part2]]
            [clojure.java.io :as io]))

(def example-input ".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............")

(deftest works
  (testing "with example input"
    (is (= 21 (solve-part1 (parse-input example-input))))
    (is (= 40 (solve-part2 (parse-input example-input)))))

  (testing "with real input"
    (let [input (parse-input (slurp (io/resource "day07.txt")))]
      (is (= 1555 (solve-part1 input)))
      (is (= 12895232295789 (solve-part2 input))))))
